# fly.toml app configuration file generated for cardio-assistant on 2025-09-07T18:46:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cardio-assistant'
primary_region = 'sjc'

[env]
  A2A_BASE_URL = "https://cardio-assistant.fly.dev"
  CLAUDE_MODEL = "claude-3-5-haiku-20241022"
  DATA_DIR = "/data"

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
